---
- name: Remove Postfix aliases
  ansible.builtin.lineinfile:
    path: "{{ pf_aliases_path }}"
    regexp: '^{{ item | regex_escape }}:'
    owner: "{{ pf_main_cf_owner }}"
    group: "{{ pf_main_cf_group }}"
    mode: '0600'
    backup: true
    state: absent
  loop: "{{ pf_remove_aliases | default([], true) }}"
  notify: Run newaliases
  tags:
    - postfix
    - config

- name: Add or modify Postfix aliases
  ansible.builtin.lineinfile:
    path: "{{ pf_aliases_path }}"
    regexp: '^{{ item.from | regex_escape }}:'
    line: "{{ item.from }}:   {{ item.to }}"
    owner: "{{ pf_main_cf_owner }}"
    group: "{{ pf_main_cf_group }}"
    mode: '0600'
    backup: true
    state: present
  loop: "{{ pf_add_aliases | default([], true) }}"
  notify: Run newaliases
  tags:
    - postfix
    - config
