---
- name: Check boolean values
  ansible.builtin.assert:
    that:
      - lookup('ansible.builtin.vars', item) | type_debug == 'bool'
    quiet: true
  when: lookup("ansible.builtin.vars", item, default=undef()) is defined
  loop:
    - pf_smtp_sasl_auth_enable
    - pf_disable_vrfy_command
    - pf_smtpd_helo_required
    - pf_strict_rfc821_envelopes
    - pf_smtpd_delay_reject
  tags:
    - postfix
    - validate

- name: Check string values
  ansible.builtin.assert:
    that:
      - litem is string
      - litem | length > 0
    quiet: true
  vars:
    litem: "{{ lookup('vars', item) }}"
  when: lookup("ansible.builtin.vars", item, default=undef()) is defined
  loop:
    - pf_inet_interfaces
    - pf_email_address
    - pf_email_password
    - pf_smtp_server
    - pf_smtp_sasl_password_maps
    - pf_mynetworks
    - pf_smtp_tls_capath
    - pf_smtp_tls_cafile
    - pf_mydomain
    - pf_smtpd_sender_login_maps
  tags:
    - postfix
    - validate

- name: Check list values
  ansible.builtin.assert:
    that:
      - litem is iterable
      - litem | length > 0
    quiet: true
  vars:
    litem: "{{ lookup('vars', item) }}"
  when: lookup("ansible.builtin.vars", item, default=undef()) is defined
  loop:
    - pf_smtp_sasl_security_options
    - pf_smtpd_helo_restrictions
    - pf_smtpd_recipient_restrictions
    - pf_smtpd_data_restrictions
  tags:
    - postfix
    - validate

- name: Check pf_smtp_sasl_security_options values
  ansible.builtin.assert:
    that:
      - item is string
      - item in pf_smtp_sasl_security_options_vv
    quiet: true
  when: pf_smtp_sasl_security_options is defined
  loop: "{{ pf_smtp_sasl_security_options }}"
  tags:
    - postfix
    - validate

- name: Check pf_smtp_tls_security_level values
  ansible.builtin.assert:
    that:
      - pf_smtp_tls_security_level is string
      - pf_smtp_tls_security_level in pf_smtp_tls_security_level_vv
    quiet: true
  when: pf_smtp_tls_security_level is defined
  tags:
    - postfix
    - validate

- name: Check pf_smtp_tls_mandatory_ciphers values
  ansible.builtin.assert:
    that:
      - pf_smtp_tls_mandatory_ciphers is string
      - pf_smtp_tls_mandatory_ciphers in pf_smtp_tls_mandatory_ciphers_vv
    quiet: true
  when: pf_smtp_tls_mandatory_ciphers is defined
  tags:
    - postfix
    - validate

- name: Check pf_inet_protocols values
  ansible.builtin.assert:
    that:
      - pf_inet_protocols is string
      - pf_inet_protocols in pf_inet_protocols_vv
    quiet: true
  when: pf_inet_protocols is defined
  tags:
    - postfix
    - validate

- name: Check integer value variables
  ansible.builtin.assert:
    that:
      - litem | int(-1) >= 0
    quiet: true
  vars:
    litem: "{{ lookup('vars', item) }}"
  when: lookup("ansible.builtin.vars", item, default=undef()) is defined
  loop:
    - pf_smtp_server_port
    - pf_smtpd_tls_loglevel
    - pf_smtp_tls_loglevel
  tags:
    - postfix
    - validate

- name: Check path variables
  ansible.builtin.assert:
    that:
      - litem is string
      - litem | length > 0
      - litem is regex(pathre)
    quiet: true
  vars:
    pathre: '^/'
    litem: "{{ lookup('vars', item) }}"
  when: lookup("ansible.builtin.vars", item, default=undef()) is defined
  loop:
    - pf_smtp_tls_capath
    - pf_smtp_tls_cafile
  tags:
    - postfix
    - validate
