---
# tasks file for postfix

- name: Include variable validation tasks
  ansible.builtin.include_tasks: assert.yml
  tags:
    - postfix
    - validate

- name: Include Postfix installation and configuration tasks
  ansible.builtin.include_tasks: postfix.yml
  tags:
    - postfix
    - install
    - config
    - service
    - validate

- name: Include aliases management tasks
  ansible.builtin.include_tasks: aliases.yml
  tags:
    - postfix
    - config
