---
- name: Run postmap
  ansible.builtin.command: "postmap {{ pf_smtp_sasl_password_maps }}"
  changed_when: true
  tags:
    - postfix
    - config

- name: Restart postfix
  ansible.builtin.service:
    name: "{{ pf_service_name }}"
    state: restarted
  when: ansible_facts['service_mgr'] == 'systemd'
  tags:
    - postfix
    - service

- name: Run newaliases
  ansible.builtin.command: newaliases
  changed_when: true
  tags:
    - postfix
    - config
