---
- name: Prepare
  hosts: all
  tasks:

    - name: Install python3-dnf on Fedora systems
      ansible.builtin.raw: dnf install -y python3-dnf sendmail
      args:
        executable: /bin/bash
      changed_when: false
      when: ansible_pkg_mgr == "dnf5"

    - name: Update Ubuntu/Debian systems
      ansible.builtin.apt:
#        upgrade: dist
        update_cache: true
        cache_valid_time: 3600
      when: ansible_pkg_mgr == "apt"
